repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents

#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v3.1.0
#    hooks:
#      - id: prettier
