/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.StationManager.shared;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertTrue(true);
    }
}
