name: Tests check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    name: Tests check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "20"

      - name: "Run tests"
        run: |
          gradle -p station_manager app:test
          gradle -p generator app:test
